services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automl-app-backend
    ports:
      - "8050:8050" 
    volumes:
      - .:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - PORT=8050
      - JWT_SECRET_KEY=your-very-secret-key-change-in-production
      - OPENROUTER_API_KEY=your_openrouter_api_key
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8050
    networks:
      - automl-network

networks:
  automl-network:
    driver: bridge